[tools]
black = "latest"
hadolint = "latest"
helm = "latest"
java = "latest"
k9s = "latest"
kubectl = "latest"
maven = "latest"
node = "latest"
pipx = "latest"
shellcheck = "latest"
shfmt = "latest"
yamllint = "latest"
ruff = "latest"
