[mgr]
prepend_keymap = [
  { on = ["m", "c"], run = "linemode mdate_perm_own", desc = "Linemode: custom (mdate+perm+own)" },
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod selected files [plugin]" },
  { on = ["u", "i"], run = "plugin restore -- --interactive", desc = "Restore interactive [plugin]" },
  { on = "+", run = "plugin zoom 1", desc = "Zoom in hovered file [plugin]" },
  { on = "-", run = "plugin zoom -1", desc = "Zoom out hovered file [plugin]" },
  { on = ["W", "p"], run = "plugin toggle-pane min-preview", desc = "Show/hide preview pane [plugin]" },
  { on = ["W", "P"], run = "plugin toggle-pane max-preview", desc = "Maximize/restore preview pane [plugin]" },
  { on = ["W", "r"], run = "plugin toggle-pane min-parent", desc = "Show/hide parent pane [plugin]" },
  { on = ["W", "R"], run = "plugin toggle-pane max-parent", desc = "Maximize/restore parent pane [plugin]" },
  { on = ["W", "c"], run = "plugin toggle-pane min-current", desc = "Show/hide current pane [plugin]" },
  { on = ["W", "C"], run = "plugin toggle-pane max-current", desc = "Max/restore current pane [plugin]" },
  { on = ["W", "n"], run = "plugin toggle-pane reset", desc = "Restore panes [plugin]" },
  { on = "M", run = "plugin mount", desc = "Mount [plugin]" },
  { on = ["g", "c"], run = "plugin vcs-files", desc = "Show git file changes [plugin]" },
  { on = ["c", "a", "a"], run = "plugin compress", desc = "Archive selected files [plugin]" },
  { on = ["c", "a", "p"], run = "plugin compress -p", desc = "Archive selected files (password) [plugin]" },
  { on = ["c", "a", "h"], run = "plugin compress -ph", desc = "Archive selected files (password+header) [plugin]" },
  { on = ["c", "a", "l"], run = "plugin compress -l", desc = "Archive selected files (compression level) [plugin]" },
  { on = ["c", "a", "u"], run = "plugin compress -phl", desc = "Archive selected files (password+header+level) [plugin]" },
  { on = ["e", "t"], run = "plugin eza-preview", desc = "Toggle tree/list dir preview [plugin]" },
  { on = ["e", "+"], run = "plugin eza-preview inc-level", desc = "Increment tree level [plugin]" },
  { on = ["e", "-"], run = "plugin eza-preview dec-level", desc = "Decrement tree level [plugin]" },
  { on = ["e", "$"], run = "plugin eza-preview toggle-follow-symlinks", desc = "Toggle tree follow symlinks [plugin]" },
  { on = ["e", "*"], run = "plugin eza-preview toggle-hidden", desc = "Toggle hidden files [plugin]" },
  { on = ["e", "g", "i"], run = "plugin eza-preview toggle-git-ignore", desc = "Toggle .gitignore files [plugin]" },
  { on = ["e", "g", "s"], run = "plugin eza-preview toggle-git-status", desc = "Toggle showing git status [plugin]" },
  { on = ["c", "s"], run  = "plugin what-size", desc = "Calc size of selection or cwd [plugin]" },
  { on = ["R", "b"], run = "plugin recycle-bin", desc = "Open Recycle Bin menu [plugin]" },
  { on = ["F", "G"], run = "plugin yafg", desc = "Open YAFG [plugin]" },
  { on = ["F", "F"], run = "plugin smart-filter", desc = "Smart filter [plugin]" },
  { on = ["c", "r"], run = "plugin path-from-root", desc = "Copies path from git root [plugin]" },
  { on = "H", run = "plugin duckdb -1", desc = "Scroll one column to the left [plugin]" },
  { on = "L", run = "plugin duckdb +1", desc = "Scroll one column to the right [plugin]" },
  { on = ["<C-w>"], run = "plugin close-and-restore-tab close_to_left", desc = "Close the current tab and turn to left tab, or quit if it is last tab [plugin]" },
  { on = ["<C-t>"], run = "plugin close-and-restore-tab restore", desc = "Restore the closed tab [plugin]" },
]

