[mgr]
ratio = [1, 5, 2]
# check init.lua for definition
linemode = "mdate_perm_own"
show_hidden = true

[open]
prepend_rules = [
  { mime = "text/html", use = [ "edit", "open", "reveal" ] },
  { url = "*.html", use = [ "edit", "open", "reveal" ] },
  { url = "*.htm", use = [ "edit", "open", "reveal" ] },
]

[plugin]
prepend_fetchers = [
  # git.yazi
  { id  = "git", url = "*", run = "git" },
  { id  = "git", url = "*/", run = "git" },
]
prepend_previewers = [
  { url = "*/", run = "eza-preview" },
  { url = "*.{csv,json,md,rst,ipynb}", run = "rich-preview" },
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo"},
  { mime = "application/subrip", run = "mediainfo" },
  # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
  { mime = "application/postscript", run = "mediainfo" },
]
prepend_preloaders = [
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
  { mime = "application/postscript", run = "mediainfo" },
]

# For a large file like Adobe Illustrator, Adobe Photoshop, etc
# you may need to increase the memory limit if no image is rendered.
# https://yazi-rs.github.io/docs/configuration/yazi#tasks
[tasks]
image_alloc = 1073741824 # = 1024*1024*1024 = 1024MB
